name: Check Automerge Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Automerge label
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Automerge') }}
        run: |
          echo "❌ Automerge label is missing"
          exit 1
