name: Check Automerge Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Automerge label
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Automerge') }}
        run: |
          echo "❌ Automerge label is missing"
          exit 1
  automerge:
    needs: check-label
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "{pullRequest.title}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"

permissions:
  contents: write
  pull-requests: write
