name: Check Automerge Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  validate-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unauthorized Automerge label
        if: |
          contains(github.event.pull_request.labels.*.name, 'Automerge') &&
          github.event.sender.login != 'YOUR_GITHUB_USERNAME'
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/Automerge"
          echo "❌ Removed unauthorized Automerge label"
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Automerge label
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'Automerge') }}
        run: |
          echo "❌ Automerge label is missing"
          exit 1
  automerge:
    needs: check-label
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Wait for lint
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'lint'
          wait-interval: 10

      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'build'
          wait-interval: 10

      - name: Wait for test
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: 'test'
          wait-interval: 10

      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Automerge"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "{pullRequest.title}"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"

permissions:
  contents: write
  pull-requests: write
