name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  check-automerge-label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && (github.event.action == 'labeled' || github.event.action == 'unlabeled'))
    outputs:
      has-automerge: ${{ steps.check-label.outputs.has-automerge }}
    steps:
      - name: Check for Automerge label
        id: check-label
        run: |
          labels=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
            | jq -r '.[].name')
          if echo "$labels" | grep -q "^Automerge$"; then
            echo "has-automerge=true" >> $GITHUB_OUTPUT
            echo "Automerge label is present"
            exit 0
          else
            echo "has-automerge=false" >> $GITHUB_OUTPUT
            echo "Automerge label is missing"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Enable Corepack
      run: corepack enable

    - name: Set Yarn version
      run: yarn set version 4.5.1

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run lint
      run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Enable Corepack
      run: corepack enable

    - name: Set Yarn version
      run: yarn set version 4.5.1

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build
      run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Enable Corepack
      run: corepack enable

    - name: Set Yarn version
      run: yarn set version 4.5.1

    - name: Get Yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run tests
      run: yarn test:run

  auto-merge:
    needs: [check-automerge-label, lint, build, test]
    runs-on: ubuntu-latest
    if: |
      needs.check-automerge-label.outputs.has-automerge == 'true' &&
      (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
    steps:
      - name: Auto-merge pull request
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge" \
            -d '{"merge_method":"squash"}'
